### PR TITLE
[metadata] add metric for failed shards

### LINKED ISSUE #633: Add more metrics along the query path
There should be more than just async operation related metrics along the query path.

For example, when we ask the elasticsearch metadata backend for what series exist there should be metrics around whether or not the response contains any failure such as failed shards.

### PR DESCRIPTION
**Pull request by dmichel1**
The `failed-es-shards` metric can be used to track how often an elasticsearch shard fails.

Ideally this metric would be added to an elasticsearch specific metric reporter but that framework doesn't currently exist.

Closes #633

### CODE REVIEW

**Comment by dmichel1** [comment]
I added a unit test for the metric being incremented when there is a failure.

File: statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetadataBackendReporter.java [hunk 1]
```diff
@@ -74,17 +75,21 @@ public SemanticMetadataBackendReporter(SemanticMetricRegistry registry) {
...
         entries = registry.counter(base.tagged("what", "entries", "unit", Units.COUNT));
 
         writesDroppedByCacheHit = registry.counter(
             base.tagged("what", "writes-dropped-by-cache-hit", "unit", Units.COUNT));
         writesDroppedByDuplicate = registry.counter(
             base.tagged("what", "writes-dropped-by-duplicate", "unit", Units.COUNT));
 
+        // only relevant to es backend.
+        failedShards = registry.counter(
+            base.tagged("what", "failed-es-shards", "unit", Units.COUNT));
```
Comment (hexedpackets) [inline statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetadataBackendReporter.java:92]: Since this is only for metadata, can we add a tag for that - `component=metadata` or something?

Comment (dmichel1) [reply statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetadataBackendReporter.java:92]: @hexedpackets that's already done above on line 64. 

` final MetricId base = MetricId.build().tagged("component", COMPONENT);`
